# 우아한 테크 캠프 TIL - 2023.08.09 (수)

## 스프링 트랜잭션 (2)

### 트랜잭션 전파 속성 복습

**Required**
외부 스코프 트랜잭션과 내부 스코프 트랜잭션 모두 `Required` 로 설정하였다.

- 기존에 생성된 트랜잭션이 존재할 경우, 기존 트랜잭션에 참여한다.
```
Found thread-bound EntityManager [SessionImpl(681904368<open>)] for JPA transaction
Participating in existing transaction
```

- 여러 논리 트랜잭션이 하나의 물리 트랜잭션에 속하므로, 내부 스코프 트랜잭션이 롤백하면 외부 스코프 트랜잭션에 영향을 미친다.

**RequiresNew**
외부 스코프 트랜잭션은 `Required`,  내부 스코프 트랜잭션은 `RequiresNew` 로 설정하였다.

- 기존에 생성된 트랜잭션이 존재할 경우 다음의 로직을 호출하여 트랜잭션 전파 속성을 확인한다
```java
// AbstractPlatformEntityManager
if (isExistingTransaction(transaction)) {
    // Existing transaction found -> check propagation behavior to find out how to behave.
    return handleExistingTransaction(def, transaction, debugEnabled);
}
```

- 트랜잭션 전파 속성이 `RequiredNew` 일 경우, 기존 트랜잭션을 중단하고 새로운 트랜잭션을 시작한다
```java
if (definition.getPropagationBehavior() == TransactionDefinition.PROPAGATION_REQUIRES_NEW) {
    SuspendedResourcesHolder suspendedResources = suspend(transaction);
    try {
        return startTransaction(definition, transaction, debugEnabled, suspendedResources);
    }
    catch (RuntimeException | Error beginEx) {
        resumeAfterBeginException(transaction, suspendedResources, beginEx);
        throw beginEx;
    }
}
```

### 에러 원인 찾기

지금까지 공부한 내용을 바탕으로 유추해보면, `Repository` 메서드 스코프의 트랜잭션에서 에러가 발생했기 때문에, `Service` 스코프의 트랜잭션이 롤백된 것이다.
자세한 경위 파악을 위해 로그 레벨을 `DEBUG` 로 변경해보았다.

**`Repository` 스코프 트랜잭션 롤백**
```
Participating transaction failed - marking existing transaction as rollback-only
Setting JPA transaction on EntityManager [SessionImpl(681904368<open>)] rollback-only
JDBC transaction marked for rollback-only (exception provided for stack trace)
```
- `CarProductRepository.findByMemberIdAndProductId` 에서 에러가 발생하여 트랜잭션이 롤백되었다.
  - `RuntimeException` 이 메서드 밖으로 던져졌고, 이를 서비스 계층에서 `try-catch` 처리함
- 트랜 잭션 전파 기본 속성인 `Required` 를 사용하고 있으므로, 외부 스코프인 `Service` 에서 생성한 트랜잭션이 `rollback-only` 로 마킹되었다.
- 내부 스코프 트랜잭션 수행 중 에러가 발생하여 롤백 되었으나, `Service` 계층 트랜잭션이 바로 롤백되지 않고 계속 수행된다.


- 예외가 발생했던 `CartProductRepository.findOnyByMemberIdAndProductId` 의 구현은 다음과 같았다.
```java
@Transactional(readOnly = true)
public CartProduct findOneByMemberIdAndProductId(Long memberId, Long productId) {
    try {
        return entityManager.createQuery(
            "select c from CartProduct c where c.member.id = :memberId and c.product.id = :productId", CartProduct.class)
	.setParameter("productId", productId)
	.setParameter("memberId", memberId)
	// 조회 결과가 없으면 NoResulException 발생 !
	.getSingleResult();
    } catch (NoResultException e) {
        throw new CartException(e.getMessage());
    }
}
```

**`Service` 스코프 트랜잭션 롤백**
```
Initiating transaction commit
Committing JPA transaction on EntityManager [SessionImpl(681904368<open>)]
committing
On commit, transaction was marked for roll-back only, rolling back
```
- 서비스 계층 스코프에서 생성한 트랜잭션에 리포지토리 계층 트랜잭션이 참가하였고, 에러로 인해 롤백되었다.
- 리포지토리 계층 스코프의 트랜잭션이 롤백될 때, 기존 트랜잭션이 `rollback-only` 로 마킹되었다.
- 따라서 서비스 계층 스코프의 트랜잭션이 커밋을 시도할 때, `rollback-only` 로 인해 `UnexpectedRollbackException` 이 던져진다.

**의문점**

왜 외부 스코프 트랜잭션은 내부 스코프 트랜잭션이 롤백되자마자 동시에 롤백되지 않을까 ?

디버깅을 통해 전체 메소드 호출 과정을 살펴보니 다음과 같았다.

1. `Service` 트랜잭션 시작
2. `Service.addProduct` 메소드 호출
3. `Repository.findByMemberIdAndProductId` 에서 예외 발생, 트랜잭션 롤백, `rollback-only` 설정
4. `Service.addProduct` 메소드에서 `Repository.findByMemberIdAndProductId` 에서 던진 예외를 처리하므로, `addProduct` 는 여전히 정상 수행
5. `Service.addProduct` 수행 종료
6. `Service` 트랜잭셔 커밋하려고 보니 `rollback-only` 설정 확인, `UnexpectedRollbackException` 던짐

서비스 계층에서 예외를 처리하여 상위 계층에서 퍼지지 않기 때문에, 서비스 트랜잭션에는 영향을 주지 않았다.

### 정리하기

**그렇다면 왜?**

이제 왜 처음에 둘 중 하나의 계층에만 `@Transaction` 을 유지했을 때 정상 작동했는지 알 수 있다.

1. 서비스 계층에만 트랜잭션을 설정한 경우
- 리포지토리에서 발생한 예외를 서비스 계층에서 `catch` 하기 때문에, 서비스 계층은 에러 없이 정상 작동한다.
- 따라서 트랜잭션은 롤백되지 않는다.

2. 리포지토리 계층에만 트랜잭션을 설정한 경우
- 리포지토리 계층의 각 메서드가 호출될 때마다 새로운 트랜잭션이 생성 후 롤백된다.
- 리포지토리 계층에서 생성되는 트랜잭션은 서로 다른 트랜잭션기 때문에 롤백에 의한 영향을 받지 않는다. 따라서 정상 작동한다.

**확장하기**

문제를 분석하면서 추가적으로 다음과 같은 해결 방법들이 따올랐다.

1. `findOneByMemberIdAndProductId` 메서드가 `CarException` 에 대해 롤백하지 않도록 설정한다.
```java
@Transactional(readOnly = true, noRollbackFor = {CartException.class})
```
- `CartException` 은 `RuntimeException` 을 상속받은 비검사 예외이기 때문에, 별도의 설정이 없다면 트랜잭션이 롤백된다
- `CartException` 이 발생해도 롤백하지 않도록 명시적으로 기입한다
  - 실행 결과 정상 작동하였다 !

2. `CartProductRepository` 의 트랜잭션 영속성 전이를 기본 설정인 `Required` 가 아닌 `RequiresNew` 로 변경한다.
```java
@Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
```
- `RequiresNew` 는 독립적인 새로운 트랜잭션을 생성하기 때문에, 해당 트랜잭션의 롤백이 다른 트랜잭션에 영향을 주지 않는다
  - 실행 결과 정상 작동하였다 !